---
abstract: 'task to install dist-zilla and all its plugins'
author:
  - 'Jerome Quelin'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Dist-Zilla
provides:
  Task::Dist::Zilla:
    file: lib/Task/Dist/Zilla.pm
    version: 1.110760
requires:
  Dist::Zilla: 0
  Dist::Zilla::Plugin::ApacheTest: 0
  Dist::Zilla::Plugin::ApocalypseTests: 0
  Dist::Zilla::Plugin::AppendExternalData: 0
  Dist::Zilla::Plugin::ArchiveRelease: 0
  Dist::Zilla::Plugin::AssertOS: 0
  Dist::Zilla::Plugin::Author::KENTNL::DistINI: 0
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::AutoMetaResources: 0
  Dist::Zilla::Plugin::AutoVersion::Relative: 0
  Dist::Zilla::Plugin::BeJROCKWAY: 0
  Dist::Zilla::Plugin::Bootstrap::lib: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::BuildFile: 0
  Dist::Zilla::Plugin::BumpVersionFromGit: 0
  Dist::Zilla::Plugin::CPANChangesTests: 0
  Dist::Zilla::Plugin::CSJEWELL::AuthorTest: 0
  Dist::Zilla::Plugin::CSJEWELL::BeforeBuild: 0
  Dist::Zilla::Plugin::CSJEWELL::DotFileFix: 0
  Dist::Zilla::Plugin::CSJEWELL::FTPUploadToOwnSite: 0
  Dist::Zilla::Plugin::CSJEWELL::SubversionDist: 0
  Dist::Zilla::Plugin::CSJEWELL::VersionGetter: 0
  Dist::Zilla::Plugin::Catalyst: 0
  Dist::Zilla::Plugin::Catalyst::New: 0
  Dist::Zilla::Plugin::ChangelogFromGit: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckChangesTests: 0
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::CheckPrereqsIndexed: 0
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::Conflicts: 0
  Dist::Zilla::Plugin::ConsistentVersionTest: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::CopyMakefilePLFromBuild: 0
  Dist::Zilla::Plugin::CopyReadmeFromBuild: 0
  Dist::Zilla::Plugin::CopyTo: 0
  Dist::Zilla::Plugin::CriticTests: 0
  Dist::Zilla::Plugin::CustomLicense: 0
  Dist::Zilla::Plugin::Deb::VersionFromChangelog: 0
  Dist::Zilla::Plugin::DistManifestTests: 0
  Dist::Zilla::Plugin::Doppelgaenger: 0
  Dist::Zilla::Plugin::DualBuilders: 0
  Dist::Zilla::Plugin::DualLife: 0
  Dist::Zilla::Plugin::DynamicManifest: 0
  Dist::Zilla::Plugin::EOLTests: 0
  Dist::Zilla::Plugin::FatPacker: 0
  Dist::Zilla::Plugin::FileKeywords: 0
  Dist::Zilla::Plugin::FileKeywords::Standard: 0
  Dist::Zilla::Plugin::FindDirByRegex: 0
  Dist::Zilla::Plugin::GatherFromManifest: 0
  Dist::Zilla::Plugin::Git: 0
  Dist::Zilla::Plugin::Git::Check: 0
  Dist::Zilla::Plugin::Git::Commit: 0
  Dist::Zilla::Plugin::Git::CommitBuild: 0
  Dist::Zilla::Plugin::Git::DescribeVersion: 0
  Dist::Zilla::Plugin::Git::Init: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::Git::Push: 0
  Dist::Zilla::Plugin::Git::Tag: 0
  Dist::Zilla::Plugin::Git::Tag::ForRelease: 0
  Dist::Zilla::Plugin::GitFmtChanges: 0
  Dist::Zilla::Plugin::GitHub: 0
  Dist::Zilla::Plugin::GitHub::Create: 0
  Dist::Zilla::Plugin::GitHub::Meta: 0
  Dist::Zilla::Plugin::GitHub::Update: 0
  Dist::Zilla::Plugin::GitObtain: 0
  Dist::Zilla::Plugin::GitVersionCheckCJM: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::GithubUpdate: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::Homepage: 0
  Dist::Zilla::Plugin::Inject: 0
  Dist::Zilla::Plugin::InlineFilesMARCEL: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::JSAN: 0
  Dist::Zilla::Plugin::JSAN::Bundle: 0
  Dist::Zilla::Plugin::JSAN::GatherDir::Template: 0
  Dist::Zilla::Plugin::JSAN::GitHubDocs: 0
  Dist::Zilla::Plugin::JSAN::InstallInstructions: 0
  Dist::Zilla::Plugin::JSAN::Minter: 0
  Dist::Zilla::Plugin::JSAN::NPM: 0
  Dist::Zilla::Plugin::JSAN::NPM::Publish: 0
  Dist::Zilla::Plugin::JSAN::PkgVersion: 0
  Dist::Zilla::Plugin::JSAN::ReadmeFromMD: 0
  Dist::Zilla::Plugin::JSAN::StaticDir: 0
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::LatestPrereqs: 0
  Dist::Zilla::Plugin::LocaleMsgfmt: 0
  Dist::Zilla::Plugin::MakeMaker::Awesome: 0
  Dist::Zilla::Plugin::MakeMaker::SkipInstall: 0
  Dist::Zilla::Plugin::MatchManifest: 0
  Dist::Zilla::Plugin::Mercurial: 0
  Dist::Zilla::Plugin::Mercurial::Check: 0
  Dist::Zilla::Plugin::Mercurial::Push: 0
  Dist::Zilla::Plugin::Mercurial::Tag: 0
  Dist::Zilla::Plugin::MetaData::BuiltWith: 0
  Dist::Zilla::Plugin::MetaData::BuiltWith::All: 0
  Dist::Zilla::Plugin::MetaProvides: 0
  Dist::Zilla::Plugin::MetaProvides::Class: 0
  Dist::Zilla::Plugin::MetaProvides::FromFile: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 0
  Dist::Zilla::Plugin::MetaResourcesFromGit: 0
  Dist::Zilla::Plugin::Metadata: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::ModuleBuild::Custom: 0
  Dist::Zilla::Plugin::ModuleBuild::XSOrPP: 0
  Dist::Zilla::Plugin::ModuleInstall: 0
  Dist::Zilla::Plugin::NoAutomatedTesting: 0
  Dist::Zilla::Plugin::NoSmartCommentsTests: 0
  Dist::Zilla::Plugin::NoTabsTests: 0
  Dist::Zilla::Plugin::OSPrereqs: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::PerlTidy: 0
  Dist::Zilla::Plugin::PickyPodWeaver: 0
  Dist::Zilla::Plugin::PodLinkTests: 0
  Dist::Zilla::Plugin::PodLoom: 0
  Dist::Zilla::Plugin::PodPurler: 0
  Dist::Zilla::Plugin::PodSpellingTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::Prepender: 0
  Dist::Zilla::Plugin::ProgCriticTests: 0
  Dist::Zilla::Plugin::PurePerlTests: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReadmeMarkdownFromPod: 0
  Dist::Zilla::Plugin::ReportPhase: 0
  Dist::Zilla::Plugin::ReportVersions: 0
  Dist::Zilla::Plugin::ReportVersions::Tiny: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::RequiresExternal: 0
  Dist::Zilla::Plugin::Rsync: 0
  Dist::Zilla::Plugin::Run: 0
  Dist::Zilla::Plugin::Run::AfterBuild: 0
  Dist::Zilla::Plugin::Run::AfterRelease: 0
  Dist::Zilla::Plugin::Run::BeforeBuild: 0
  Dist::Zilla::Plugin::Run::BeforeRelease: 0
  Dist::Zilla::Plugin::Run::Release: 0
  Dist::Zilla::Plugin::Run::Role::Runner: 0
  Dist::Zilla::Plugin::SVK: 0
  Dist::Zilla::Plugin::SVK::Check: 0
  Dist::Zilla::Plugin::SVK::Commit: 0
  Dist::Zilla::Plugin::SVK::Push: 0
  Dist::Zilla::Plugin::SVK::Tag: 0
  Dist::Zilla::Plugin::Signature: 0
  Dist::Zilla::Plugin::StaticVersion: 0
  Dist::Zilla::Plugin::SubmittingPatches: 0
  Dist::Zilla::Plugin::Subversion: 0
  Dist::Zilla::Plugin::Subversion::ReleaseDist: 0
  Dist::Zilla::Plugin::Subversion::Tag: 0
  Dist::Zilla::Plugin::SurgicalPkgVersion: 0
  Dist::Zilla::Plugin::SurgicalPodWeaver: 0
  Dist::Zilla::Plugin::SvnObtain: 0
  Dist::Zilla::Plugin::SynopsisTests: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::TemplateCJM: 0
  Dist::Zilla::Plugin::TemplateFiles: 0
  Dist::Zilla::Plugin::Twitter: 0
  Dist::Zilla::Plugin::UnusedVarsTests: 0
  Dist::Zilla::Plugin::UpdateGitHub: 0
  Dist::Zilla::Plugin::VersionFromModule: 0
  Dist::Zilla::Plugin::WSDL: 0
  Dist::Zilla::Plugin::WSDL::Types: 0
  Dist::Zilla::PluginBundle::AJGB: 0
  Dist::Zilla::PluginBundle::AVAR: 0
  Dist::Zilla::PluginBundle::Author::DOHERTY: 0
  Dist::Zilla::PluginBundle::Author::KENTNL: 0
  Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 0
  Dist::Zilla::PluginBundle::Author::LESPEA: 0
  Dist::Zilla::PluginBundle::Author::OLIVER: 0
  Dist::Zilla::PluginBundle::BINGOS: 0
  Dist::Zilla::PluginBundle::CEBJYRE: 0
  Dist::Zilla::PluginBundle::CJM: 0
  Dist::Zilla::PluginBundle::CSJEWELL: 0
  Dist::Zilla::PluginBundle::DAGOLDEN: 0
  Dist::Zilla::PluginBundle::DANIELP: 0
  Dist::Zilla::PluginBundle::DOY: 0
  Dist::Zilla::PluginBundle::FAYLAND: 0
  Dist::Zilla::PluginBundle::FLORA: 0
  Dist::Zilla::PluginBundle::GENEHACK: 0
  Dist::Zilla::PluginBundle::GETTY: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::PluginBundle::GitHub: 0
  Dist::Zilla::PluginBundle::GopherRepellent: 0
  Dist::Zilla::PluginBundle::IDOPEREL: 0
  Dist::Zilla::PluginBundle::JQUELIN: 0
  Dist::Zilla::PluginBundle::JROCKWAY: 0
  Dist::Zilla::PluginBundle::MARCEL: 0
  Dist::Zilla::PluginBundle::MSCHOUT: 0
  Dist::Zilla::PluginBundle::Mercurial: 0
  Dist::Zilla::PluginBundle::NIGELM: 0
  Dist::Zilla::PluginBundle::NUFFIN: 0
  Dist::Zilla::PluginBundle::PDONELAN: 0
  Dist::Zilla::PluginBundle::PadrePlugin: 0
  Dist::Zilla::PluginBundle::RBO: 0
  Dist::Zilla::PluginBundle::RBUELS: 0
  Dist::Zilla::PluginBundle::RJBS: 0
  Dist::Zilla::PluginBundle::ROKR: 0
  Dist::Zilla::PluginBundle::ROKR::Basic: 0
  Dist::Zilla::PluginBundle::RTHOMPSON: 0
  Dist::Zilla::PluginBundle::Rakudo: 0
  Dist::Zilla::PluginBundle::SVK: 0
  Dist::Zilla::PluginBundle::TestingMania: 0
  Dist::Zilla::PluginBundle::WOLVERIAN: 0
  Dist::Zilla::PluginBundle::YANICK: 0
  perl: 5.008
resources:
  X_mailing_list: http://www.listbox.com/subscribe/?list_id=139292
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-Dist-Zilla
  homepage: http://search.cpan.org/dist/Task-Dist-Zilla/
  repository: git://github.com/jquelin/task-dist-zilla.git
version: 1.110760
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@JQUELIN/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@JQUELIN/PruneFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@JQUELIN/AutoPrereqs'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@JQUELIN/TaskWeaver'
      version: 0.101621
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.17
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.12044908
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@JQUELIN/MetaJSON'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git::Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git::Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@JQUELIN/Git::CommitBuild'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/TagMaster'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/TagRelease'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git::Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
